### PR TITLE
Add XDT Transform Visitor and command line interface

### PR DESCRIPTION
**Pull request by keith-hall**
Hi,

Thanks for this great library! I've added a command line interface project for easier consumption, and the ability to generate an [XML Document Transformation file](https://msdn.microsoft.com/en-us/library/dd465326%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396), and thought I'd show you my changes in case you want to include them upstream.

My main use case is for comparing .NET configuration files from Production environments (i.e. not under my control) to those in the development environment. Using this tool allows me to ensure that I can keep the deployment steps (under source control) for my projects up to date without accidentally undoing any config changes made by others. ;)

### CODE REVIEW

**Comment by ashapkin** [comment]
Wow! Thanks, pal! It's really nice that somebody was able to find this small old repo and most importantly to get some benefits from it. I will merge your PR within a few days.

Btw, I recently visited Vilnius during my small NY trip for a couple of days. Very unique and beautiful city :D

**Comment by keith-hall** [comment]
Great to hear that Aleksandr! Was there lots of snow while you were in Vilnius? :)

No hurry with merging, I just realized that I should add some tests to confirm that my changes are working as intended ;)
In the interest of full transparency, and to get your opinion, I was thinking of converting this library to a .NET Standard 2.0 project, and the console app to .NET Core 2.0 - would you be amenable to such a change (as part of a separate PR, of course)? :) I feel such a change could make this library more accessible, as it would then be usable cross platform - and I'm considering integrating it with a [Sublime Text 3 plugin](https://github.com/keith-hall/SublimeDotNetConfig) I'm working on. But before I do that, it'd be super handy if we could settle on a license for the code in this repo please :)

**Comment by ashapkin** [comment]
@keith-hall 
Sry for the delay, I made some refactoring to XdtVisitor and wanted to pull changes here, but occasionally created a new branch (https://github.com/ashapkin/XmlDiff/compare/forkeith-xdt-console). Need more practice with Github I guess. I need to fix some tests after refactoring btw.

> In the interest of full transparency, and to get your opinion, I was thinking of converting this library to a .NET Standard 2.0 project, and the console app to .NET Core 2.0 - would you be amenable to such a change (as part of a separate PR, of course)

Sure, why not? :)

> it'd be super handy if we could settle on a license for the code in this repo

Any thoughts about the license? I would like to use MIT or Apache.

**Comment by keith-hall** [comment]
Nice, your refactor makes it much easier to follow the logic and see what's happening :) if you need any help with the tests, please let me know :)

I tend to use the MIT license for my projects, but looking at https://choosealicense.com/licenses/, Apache seems cool too - I like the idea that changes must be documented.

**Comment by ashapkin** [comment]
Thanks, Keith! 

I will take a look into license and new project structure.

**Pull request merged**
